# -*- coding: utf-8 -*-

import sys
import time

def Menu():
    sys.stdout.write("\033[1;1H")
    sys.stdout.write("\033[2J")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print("            Panique en cuisine !")
    print(" ")
    choix = input('    Appuyer sur Entrer pour continuer')
    sys.stdout.write("\033[1;1H")
    sys.stdout.write("\033[2J")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print("      Bienvenue dans le jeu Panique en cuisine !")
    time.sleep(3)
    sys.stdout.write("\033[1;1H")
    sys.stdout.write("\033[2J")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print("Le but de ce jeu est d'empêcher les monstres d'atteindre le bas de la cuisine")
    time.sleep(4)
    sys.stdout.write("\033[1;1H")
    sys.stdout.write("\033[2J")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print("Pour cela, utilisez les touches Z, Q, S et D pour vous déplacer et R pour tirer")
    time.sleep(6)
    sys.stdout.write("\033[1;1H")
    sys.stdout.write("\033[2J")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print("Plus vous tuez de monstres, plus votre score augmente !")
    time.sleep(4)
    sys.stdout.write("\033[1;1H")
    sys.stdout.write("\033[2J")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print("Vous pouvez utiliser votre attaque spéciale avec la touche P, mais elle vous enlevera des points")
    time.sleep(5)
    sys.stdout.write("\033[1;1H")
    sys.stdout.write("\033[2J")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print("            Bonne chance à vous !")
    print(" ")
    choix = input('   Appuyer sur Entrer pour lancer le jeu')
    sys.stdout.write("\033[1;1H")
    sys.stdout.write("\033[2J")

